# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name="Answer's text")),
                ('is_valid', models.BooleanField(default=False, help_text='tick if answer is correct choice')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=64, verbose_name='Exam name')),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(blank=True, max_length=64, null=True, verbose_name='Subject name')),
                ('year', models.IntegerField(blank=True, verbose_name='Exam Year')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Subject Duration')),
            ],
            options={
                'verbose_name_plural': 'ExamSubjects',
                'verbose_name': 'ExamSubject',
                'ordering': ['exam', 'subject', 'year'],
            },
        ),
        migrations.CreateModel(
            name='LeadersBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=20, verbose_name='total points')),
            ],
            options={
                'verbose_name_plural': 'LeadersBoard',
                'verbose_name': 'LeaderBoard',
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=30000, verbose_name="Question's text")),
                ('serial_no', models.IntegerField(help_text='Questions will be shown based on their index, and this index is shown as the question number', unique=True, verbose_name="Question's index")),
                ('is_published', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.ExamSubject')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
                'ordering': ['serial_no'],
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20, verbose_name='my score')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myscores', to='learn.ExamSubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myscores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserScores',
                'verbose_name': 'UserScore',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='leadersboard',
            name='user_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadersboard', to='learn.UserScore'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learn.Question'),
        ),
    ]
