# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170123_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Exam Body Name')),
                ('logoUrl', models.ImageField(blank=True, upload_to='staff', verbose_name='Exam Body Logo')),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English Language'), ('math', 'Mathematics'), ('geography', 'Geography'), ('chemistry', 'Chemistry'), ('physics', 'Physics')], max_length=40)),
                ('startDate', models.IntegerField(blank=True, verbose_name='Start of Exam Years')),
                ('stopDate', models.IntegerField(blank=True, verbose_name='End of Exam Years')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name="Answer's text"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name="Question's text"),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myscoresexam', to='learn.ExamSubject'),
        ),
    ]
