# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20170213_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name="Correct Answer's text"),
        ),
        migrations.AlterField(
            model_name='question',
            name='serial_no',
            field=models.IntegerField(help_text='Questions will be shown based on their index', verbose_name="Question's index"),
        ),
    ]
